name: "my-website"
navbar:
  title: "Directory"
  type: inverse
  left:
    - text: "Home"
      href: index.html
    - text: "About Me"
      href: about.html
    - text: "Beer Study"
      menu:
      - text: Project EDA
        href: Project_1.html
      - text: Rshiny App
        href: https://willjones11.shinyapps.io/casestudy/
  right:
    - text: Links 
      menu:
      - text: Github
        href: https://github.com/willjones11
      - text: Linkden
        href: https://www.linkedin.com/in/williamfjones11/
        
    - text: Papers
      menu: 
      - text: LSTM CNN
        href: https://github.com/willjones11/LSTMCNN/blob/main/AI_research_paper.pdf?raw=true
      - text: Muon Radiosonde Correlation
        href: https://docs.google.com/document/d/1F7S2HmP6Gj4zTV-z1ZtOrUcDbAHgDXaW15Mef4D3so0/edit?usp=sharing
      - text: Housing Analysis
        href: https://github.com/willjones11/MSDS-6371-Project/blob/main/Jones_Bhandari_Project.pdf?raw=true
        
    - text: DDS Case Study 2
      menu:
      - text: R Markdown File
        href: https://github.com/willjones11/CaseStudy2DDS/blob/main/William_Jones_Case_Study_2(1).Rmd
      - text: Youtube Presentation
        href: https://youtu.be/MbfQbsnYQBM
html_document:
    theme: yeti
  
