name: "my-website"
navbar:
  title: "Directory"
  left:
    - text: "Home"
      href: index.html
    - text: "About Me"
      href: about.html
    - text: "Beer Study"
    menu:
    - text: Project EDA
      href: Project_1.html
    - text: Rshiny App
      href: https://willjones11.shinyapps.io/casestudy/
output:
  html_document:
    theme: yeti
      
  
