---
title: "App"
author: "William Jones"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include =FALSE}
beers = read.csv("https://github.com/willjones11/willjones11.github.io/Beers.csv")
breweries = read.csv("https://github.com/willjones11/willjones11.github.io/Breweries.csv")

```

```{r, include =FALSE}

library(ggplot2)
library(ggthemes)
library(tidyverse)
breweries %>% group_by(State) %>%
  summarise(count = n_distinct(Brew_ID)) %>%
  arrange(count) %>%
  ggplot(aes(x= reorder(State, +count), y = count)) +
  geom_bar(stat="identity", fill ="blue") +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) + 
  geom_text(aes(label=count), vjust=-0.5, color="black",
            position = position_dodge(0.9), size=2.5) +
  ylab('# of Breweries') +
  xlab('States') +
  ggtitle('# of Breweries per State') +
  theme_pander()
  

```

```{r, include =FALSE}
library(dplyr)
#first change one of the datasets column name to match the other
breweries <- breweries %>% rename("Brewery_id"= "Brew_ID")
#Change Name of brewery to avoid duplicate column names
breweries <- breweries %>% rename("Brewery" = "Name")
data <- beers %>% inner_join(breweries, by = "Brewery_id")
#printing of the first 6 rows
head(data) #first 6 rows
tail(data) # last 6 rows
summary(data)
#checking string columns for missing cell strings
print(colSums(data == ""))

```


```{r, include =FALSE}

#after filling in mising data bringing back in now filtered data frame
beer_data = read.csv("https://github.com/willjones11/willjones11.github.io/filteredData.csv")
#summary after hand searching missing data
summary(beer_data)
print(colSums(beer_data == ""))
# checking for duplicated beers
dup = beer_data[duplicated(beer_data$Name), ]
dup
sprintf("There are a total of %d duplicated rows consisting of %d different beers", sum(duplicated(beer_data$Name)),length(unique(dup$Name))) 
     
``` 

```{r, include =FALSE}
beer_data <- beer_data[!duplicated(beer_data$Name),]
beer_data
sprintf("There are now only %d beers in the dataframe", length(beer_data$Name))
```

```{r, include =FALSE}
library(ggplot2)
library(ggpubr)
library(ggthemes)
options(repr.plot.width = 10, repr.plot.height =4)

abv <- beer_data %>%
  filter(!is.na(ABV)) %>% group_by(State) %>%
  summarise(x = median(ABV)) %>%
  ggplot(aes(x= reorder(State, +x), y=x)) + 
  geom_bar(stat="identity", bins = 50, fill="skyblue1")   +
  ylab("ABV") +
  xlab(NULL) + 
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  theme_tufte()
ibu <- beer_data %>%
  filter(!is.na(IBU)) %>% group_by(State) %>%
  summarise(x = median(IBU)) %>%
  ggplot(aes(x=reorder(State, +x), y=x)) + 
  geom_bar(stat="identity", bins = 50, fill="skyblue1")  +
  xlab("State") +
  ylab("IBU") +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  
  theme_tufte()
  
#combining plots together
p <- ggarrange(abv, ibu, ncol = 1, nrow = 2, align = "v") 

annotate_figure(p, top = text_grob("Median ABV and IBU per State", face ="bold", size=16, family="serif")) + theme_tufte()
```

```{r, include =FALSE}
#options(repr.plot.width = 10, repr.plot.height =4)

beer_data %>%
  filter(!is.na(ABV)) %>% group_by(State) %>%
  summarise(x = max(ABV)) %>%
  top_n(3, x) %>%
  ggplot(aes(x= State, y=x)) + 
  geom_bar(stat="identity", fill="skyblue1")   +
  ylab("ABV") +
  xlab(NULL) +
  ggtitle('Top 3 States With Highest ABV') +
  theme_tufte()
beer_data %>%
  filter(!is.na(IBU)) %>% group_by(State) %>%
  summarise(x = max(IBU)) %>%
  top_n(3, x) %>%
  ggplot(aes(x=State, y=x)) + 
  geom_bar(stat="identity", fill="skyblue1")  +
  ylab("IBU") +
  ggtitle('Top 3 States With Highest IBU') +
  theme_tufte()
beer_data %>%
  filter(!is.na(ABV)) %>% group_by(State) %>%
  summarise(x = max(ABV)) %>% top_n(3,x)
```

```{r, include =FALSE}
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)


beer_data %>% filter(!is.na(ABV)) %>%
  ggplot(aes(x=ABV)) + 
  geom_boxplot(color="black") +
  geom_vline(aes(xintercept= mean(ABV)), color ="red") +
  geom_text(aes(mean(ABV), 0, label=paste("Mean :",round(mean(ABV), digits= 4)), vjust = -12.7, hjust = -1.99)) +
  geom_text(aes(mean(ABV), 0, label=paste("SD :",round(sd(ABV), digits= 4)), vjust = -11.5, hjust = -2.34)) +
  geom_text(aes(mean(ABV), 0, label=paste("Min :",round(min(ABV), digits= 4)), vjust = -10.3, hjust = -2.57)) +
  geom_text(aes(mean(ABV), 0, label=paste("Max :",round(max(ABV), digits= 4)), vjust = -9.2, hjust = -2.44)) +
  geom_text(aes(mean(ABV), 0, label=paste("Med :",round(median(ABV), digits= 4)), vjust = -8.1, hjust = -2.17)) +
  ggtitle("Distribution of ABV") +
  ylab(NULL) +
  theme_stata()
  
```

```{r, include =FALSE}
beer_data %>% filter(!is.na(ABV) & !is.na(IBU)) %>%
  ggplot(aes(x= ABV, y= IBU)) + 
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ggtitle(paste0("ABV vs. IBU relationship with coorleation cofficent of ", round(cor.test(beer_data$ABV,beer_data$IBU, method="pearson")$estimate, digits = 4), "\n and a pvalue : ", ... = cor.test(beer_data$ABV,beer_data$IBU, method="pearson")$p.value) ) +
  theme_tufte()
cor.test(beer_data$ABV, beer_data$IBU)[3] 
```

```{r, include =FALSE}
library(class)
library(e1071)
library(caret)
library(ggplot2)
library(dplyr)
# filtering for rows with non missing values in ABV and IBU that contain the substring 'IPA' or 'Ale', from there it is encoded to a new 
# column of type containing either the string 'IPA' or 'Ale'
beer_knn_dataset = beer_data %>%
  filter(!is.na(ABV) & !is.na(IBU) & (grepl('Ale', Style) | grepl('IPA', Style))) %>%
  mutate(Type = ifelse(!grepl('Ale', Style) ,'IPA', 'Ale'))

#creating dataframes for metrics
accs = data.frame(accuracy = numeric(25), k = numeric(25))
sens = data.frame(sensitivity = numeric(25), k = numeric(25))
spec = data.frame(specificity = numeric(25), k = numeric(25))
#Figuring out which K value to us 
for(i in 1:25)
{
  #Knn cross validation model 
  classifications = knn.cv(beer_knn_dataset[,c(3,5)],beer_knn_dataset$Type, prob = TRUE, k = i, use.all = FALSE)
  #creating a table
  table(beer_knn_dataset$Type,classifications)
  #Confusion Matrix
  CM = confusionMatrix(table(beer_knn_dataset$Type,classifications))
  #Adding the metrics to their perspective dataframes
  accs$accuracy[i] = CM$overall[1]
  sens$sensitivity[i] = CM$byClass[1]
  spec$specificity[i] = CM$byClass[2]
  #adding k value to dataframes
  accs$k[i] = i
  sens$k[i] = i
  spec$k[i] = i
}
#Plotting the metrics
ggplot() +
  geom_line(data = accs, aes(k,accuracy,  colour ="Accuracy")) +
  geom_line(data = sens ,aes(k,sensitivity,  colour ="Sensitivity")) +
  geom_line(data = spec, aes(k,specificity, colour = "Specificity")) + 
  ggtitle("ABV & IBU KNN MODEL") +
  ylab("ratio") +
  xlab("K") +
  scale_color_manual(values = c("Accuracy" = "blue", "Sensitivity" = "red", "Specificity" = "purple")) +
  labs(color = "Metric")

#KNN Cross validation model 
classifications = knn.cv(beer_knn_dataset[,c(3,5)],beer_knn_dataset$Type, prob = TRUE, k = 5, use.all=FALSE)
#Creating a Table
table(beer_knn_dataset$Type,classifications)
#Confusion Matrix 
CM = confusionMatrix(table(beer_knn_dataset$Type,classifications))
CM

```


```{r, include =FALSE}
number_beers = beer_data %>% count(State)
number_beers %>% ggplot(aes(x=reorder(State, +n), y=n)) +
  geom_bar(stat = "identity") +
  xlab("State") +
  ylab("Count") +
  ggtitle("Number of Different Beers in Each State") +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  geom_text(aes(label=n), vjust=-0.5, color="black",
            position = position_dodge(0.9), size=2.5) +
  theme_tufte()
```

```{r, include =FALSE}
top_beers =distinct(beer_data %>% group_by(State) %>% top_n(1, Style) %>% select(State, Style), State, .keep_all =TRUE)

top_beers <- top_beers %>% group_by(Style) %>% count(Style)
top_beers
top_beers$Style[1] = "Märzen / Oktoberfest"
top_beers$Style[2] = "Kölsch"
top_beers %>% ggplot(aes(y=reorder(Style, +n), x=n)) + geom_bar(stat="identity") + geom_text(aes(label=n), color="white",
          hjust=1.1, size=5) +
  ylab("Style") +
  xlab("Count") + 
  ggtitle("Count of State's Most Abundant Style of Beer") + 
  theme_tufte()
```
```{r}
# take the count of each group of ounces
temp = beer_data %>% count(Ounces)
# arrange in descending order
temp <- temp %>% arrange(desc(Ounces))
#make rows with small numbers into one group
temp$Ounces[temp$n <= 10] <- "Other"
#making ounces a character string
temp$Ounces <- as.character(temp$Ounces)
#creating a percentage column 
temp$labels <- round(temp$n / sum(temp$n) *100, digits =3 )
#combining other rows
temp = temp %>% group_by(Ounces) %>% summarize(labels = sum(labels)) %>% ungroup()
#concatentating ounces and labels column 
temp$type <- paste(temp$Ounces, " (", temp$labels, "%)" )
temp %>% ggplot(aes(x="", y=labels, fill = type)) + 
  geom_bar(stat= "identity", width=1) +
  coord_polar("y", start=0) +
  scale_fill_viridis(discrete = TRUE, name= "Ounces (Percentage)") +
  ylab(NULL) +
  xlab(NULL) +
  ggtitle("Distribution of Can Sizes") +
  theme(axis.text = element_blank(), 
        axis.ticks = element_blank(), 
        panel.grid = element_blank()) 
```

```{r}
library(shiny)


ui <- fluidPage(
  sidebarLayout(
   
    sidebarPanel(
       
      selectInput("select", "Select from dropdown list",
                    c("Beer Data"="beerdata","IBU Data" = "IBU","ABV Data" = "ABV", "IBU vs. ABV" = "IBUvsABV", "Top Beers" = "TopBeer"),
                    selected = 1),
      conditionalPanel(
        condition = "input.select == 'IBU'",
              selectInput("state1", "Choose a State",
                    choices = state.abb,
                    selected = 1),
        radioButtons("radio1","Select a plot",
                    choices = list("Histogram" = 1, "Boxplot" = 2),
                    selected = 1),
        ),
        conditionalPanel(
        condition = "input.select == 'ABV'",
              selectInput("state2", label = "Choose a State",
                    choices = state.abb,
                    selected = 1),
        radioButtons("radio2","Select a plot",
                    choices = list("Histogram" = 1, "Boxplot" = 2),
                    selected = 1),
        ),
        conditionalPanel(
        condition = "input.select == 'IBUvsABV'",
              selectInput("state3", "Choose a State",
                    choices = state.abb,
                    selected = 1),
              radioButtons("radio3","Simple Linear Regression",
                    choices = list("Yes" = 1, "No" = 2),
                    selected = 1),
        )),
      mainPanel(
          plotOutput(outputId = "distPlot"),
          textOutput("Beer Data"),
          fluidRow(
          column(12,
          dataTableOutput('table')
          )),
      )
  )
)

server <-  function(input,output) {
   
  output$distPlot <- renderPlot({
   
    merged1 <- filtereddata %>% filter(State == input$state1)

    merged2 <- filtereddata %>% filter(State == input$state2)

    merged3 <- filtereddata %>% filter(State == input$state3)
    if(input$select == "Beer Data File"){
      output$table <- renderDataTable(filtereddata,
          options = list(
          pageLength = 5)
        )
          fluidRow(
          column(12,
          dataTableOutput('table')
          ))
    }else if(input$select == "IBU" && input$radio1 == 1){
      x <- as.integer(merged1$IBU)
      bins <- seq(min(x), max(x), length.out = 20)
      hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "IBU",
         main = "Histogram of IBU Levels")
    }else if(input$select == "IBU" && input$radio1 == 2){
      boxplot(merged1$IBU, xlab = "IBU",
         main = "Boxplot of IBU Levels")
    }else if(input$select == "ABV" && input$radio2 == 1){
      x <- merged2$ABV
      bins <- seq(min(x), max(x), length.out = 20)
      hist(x, breaks = bins,ylim=c(0, .13), col = "#75AADB", border = "white",
         xlab = "IBU",
         main = "Histogram of ABV Levels")
    }else if(input$select == "ABV" && input$radio2 == 2){
      boxplot(merged2$ABV, xlab = "ABV",
         main = "Boxplot of ABV Levels")
    }else if(input$select == "IBUvsABV"  && input$radio3 == 1){
        merged3 %>% ggplot(aes(x=IBU,y=ABV)) +
        geom_point(position = "jitter") +
        geom_smooth(method = "lm") +
        ggtitle("IBU vs. ABV") +
        theme(text = element_text(size = 16))
    } else if(input$select == "IBUvsABV"  && input$radio3 == 2){
        merged3 %>% ggplot(aes(x=IBU,y=ABV)) +
        geom_point(position = "jitter") +
        ggtitle("IBU vs. ABV") +
        theme(text = element_text(size = 16))
    }
  })
}

shinyApp(ui, server)

```